sudo: false
language: python
cache: pip
python:
  - '3.8'
before_install:
  - uname -a
  - python --version
install:
  - pip install -r requirements/travis.txt
script:
  - tox -v
branches:
  only:
    - master
env:
  - TOXENV=coverage
  - TOXENV=quality
  - TOXENV=django22
  - TOXENV=django30
  - TOXENV=django31
